---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-carousel
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kargo-carousel
spec:
  subscriptions:
    warehouse: my-warehouse
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: carousel-image
  namespace: kargo-carousel
spec:
  subscriptions:
    - image:
        repoURL: registry.incompletion.ist/disimprovement/carousel