---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-carousel
spec:
  promotionPolicies:
    - stage: production
      autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kargo-carousel
spec:
  subscriptions:
    warehouse: production
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/incompletion-ist/argocd-apps
        writeBranch: kargo-testing
        kustomize:
          images:
            - image: registry.incompletion.ist/disimprovement/carousel
              path: carousel
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: production
  namespace: kargo-carousel
spec:
  subscriptions:
    - image:
        repoURL: registry.incompletion.ist/disimprovement/carousel
        digestConstraint: latest
        imageSelectionStrategy: Digest
        insecureSkipTLSVerify: true # TODO use root CA instead, but where is it?!