apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: carousel-auth
  namespace: kargo-carousel
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['carousel-auth']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carousel-auth
  namespace: kargo-carousel
subjects:
  - kind: ServiceAccount
    name: carousel-auth
    namespace: kargo-carousel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: carousel-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carousel-auth
  namespace: kargo-carousel
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: carousel-auth
  namespace: kargo-carousel
spec:
  vaultConnectionRef: vault-secrets-operator/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: carousel
    serviceAccount: carousel-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: carousel-auth
  namespace: kargo-carousel
spec:
  type: kv-v2
  mount: kv
  path: registry.incompletion.ist/disimprovement-carousel/pull-secret
  vaultAuthRef: carousel-auth
  destination:
    name: pull-secret
    create: true
    type: kubernetes.io/dockerconfigjson
