---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: production
spec:
  subscriptions:
    - image:
        repoURL: registry.incompletion.ist/disimprovement/carousel
        imageSelectionStrategy: Digest
        semverConstraint: "0.1"
        insecureSkipTLSVerify: true # TODO use root CA instead, but where is it?!