kargo:
  api:
    secret:
      name: api-secret
    host: kargo.incompletion.ist
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: kargo.incompletion.ist
        cert-manager.io/private-key-size: "4096"
      tls:
        selfSignedCert: false
    tls:
      enabled: false
      selfSignedCert: false
