apiVersion: v2
name: nginx-ingress
description: Install nginx-ingress with our configurations
type: application
version: "0.1.0"
appVersion: "3.7.0"
dependencies:
  - name: nginx-ingress
    version: "1.4.0"
    repository: oci://ghcr.io/nginxinc/charts/nginx-ingress
