apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-auth
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['kargo-auth']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-auth
subjects:
  - kind: ServiceAccount
    name: kargo-auth
    namespace: kargo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: kargo-auth
spec:
  vaultConnectionRef: vault-secrets-operator/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: kargo
    serviceAccount: kargo-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kargo-auth
spec:
  type: kv-v2
  mount: kv
  path: kargo.incompletion.ist/admin/api-secret
  vaultAuthRef: kargo-auth
  destination:
    name: api-secret
    create: true
