gitlab:
  global:
    hosts:
      domain: incompletion.ist
    ingress:
      configureCertmanager: false
    email:
      display_name: 'Incompletionist GitLab'
      from: 'gitlab@gitlab.incompletion.ist'
      reply_to: 'noreply@gitlab.incompletion.ist'
    smtp:
      enabled: true
      address: smtp.gmail.com
      port: 587
      tls: true
      domain: smtp.gmail.com
      enable_starttls_auto: true
      authentication: login
      openssl_verify_mode: peer
      user_name: admin@micah.ws
      password:
        secret: smtp-auth
        key: password
  certmanager:
    install: false
  upgradeCheck:
    enabled: false
  gitlab:
    webservice:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: vault-issuer
          cert-manager.io/private-key-size: "4096"
          cert-manager.io/common-name: gitlab.incompletion.ist
        tls:
          secretName: webservice-tls
  gitlab-runner:
    certsSecretName: cacert
