apiVersion: v2
name: vault
description: Install Vault with our configurations
type: application
version: "0.1.0"
appVersion: "1.17.2"
dependencies:
  - name: vault
    version: "0.28.1"
    repository: https://helm.releases.hashicorp.com
