apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers: null
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: argo-cd
    repoURL: https://github.com/incompletion-ist/argocd-apps.git
    targetRevision: HEAD
