apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
  finalizers: null
spec:
  description: ArgoCD Deployment
  sourceRepos:
    - https://github.com/incompletion-ist/argocd-apps
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
