---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault
  namespace: argocd
  finalizers: null
spec:
  description: Vault Deployment
  sourceRepos:
    - https://github.com/incompletion-ist/argocd-apps
  destinations:
    - namespace: vault
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers: null
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: vault
  source:
    path: vault
    repoURL: https://github.com/incompletion-ist/argocd-apps.git
    targetRevision: HEAD
