apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: github-auth
  namespace: argocd
spec:
  type: kv-v2
  mount: kv
  path: github.com/micahkemp/argocd
  destination:
    name: githib-auth
    create: true
