apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: github-micahkemp
spec:
  provider: vault
  secretObjects:
    - stringData:
        - key: type
          objectName: type
        - key: url
          objectName: url
        - key: sshPrivateKey
          objectName: sshPrivateKey
      secretName: github-micahkemp
      type: Opaque
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "argocd"
    objects: |
      - objectName: "type"
        secretPath: "kv/github.com/micahkemp/argocd"
        secretKey: "type"
      - objectName: "url"
        secretPath: "kv/github.com/micahkemp/argocd"
        secretKey: "url"
      - objectName: "sshPrivateKey"
        secretPath: "kv/github.com/micahkemp/argocd"
        secretKey: "sshPrivateKey"
