apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: github-micahkemp
spec:
  provider: vault
  secretObjects:
    - data:
      - key: private_key
        objectName: github-micahkemp
      secretName: github-micahkemp
      type: Opaque
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "argocd"
    objects: |
      - objectName: "github-micahkemp"
        secretPath: "kv/github.com/micahkemp/argocd"
        secretKey: "private_key"
