---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: longhorn
  namespace: argocd
  finalizers: null
spec:
  description: Longhorn Deployment
  sourceRepos:
    - https://github.com/incompletion-ist/argocd-apps.git
  destinations:
    - namespace: longhorn-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers: null
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: longhorn
  source:
    path: longhorn
    repoURL: https://github.com/incompletion-ist/argocd-apps.git
    targetRevision: k3s
