---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers: null
spec:
  description: nginx-ingress Deployment
  sourceRepos:
    - https://github.com/incompletion-ist/argocd-apps.git
  destinations:
    - namespace: nginx-ingress
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers: null
spec:
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  project: nginx-ingress
  source:
    path: nginx-ingress
    repoURL: https://github.com/incompletion-ist/argocd-apps.git
    targetRevision: k3s
