---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault-secrets-operator
  namespace: argocd
  finalizers: null
spec:
  description: vault-secrets-operator Deployment
  sourceRepos:
    - git@github.com:incompletion-ist/argocd-apps.git
  destinations:
    - namespace: vault-secrets-operator
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  finalizers: null
spec:
  destination:
    namespace: vault-secrets-operator
    server: https://kubernetes.default.svc
  project: vault-secrets-operator
  source:
    path: vault-secrets-operator
    repoURL: git@github.com:incompletion-ist/argocd-apps.git
    targetRevision: k3s
