apiVersion: apps/v1
kind: Deployment
metadata:
  name: carousel
  labels:
    app.kubernetes.io/name: carousel
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: carousel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: carousel
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: carousel
        image: registry.gitlab.com/micahkemp/carousel:0.0.1
        args:
          - /config/config.json
        ports:
          - containerPort: 8888
        volumeMounts:
          - mountPath: /config
            name: config
            readOnly: true
          - mountPath: "/data"
            name: storage
      imagePullSecrets:
        - name: pull-secret-gitlab-com
      volumes:
        - name: config
          secret:
            secretName: config-secret
        - name: storage
          persistentVolumeClaim:
            claimName: storage
