apiVersion: apps/v1
kind: Deployment
metadata:
  name: carousel
  labels:
    app.kubernetes.io/name: carousel
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: carousel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: carousel
    spec:
      containers:
      - name: carousel
        image: registry.incompletion.ist/disimprovement/carousel:0.0.1
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: pull-secret
