apiVersion: v2
name: cert-manager
description: Install cert-manager with our configuration
type: application
version: 0.1.0
appVersion: "1.15.1"
dependencies:
  - name: cert-manager
    version: v1.15.1
    repository: https://charts.jetstack.io
